BEGIN;

INSERT INTO users VALUES
  (1, 'steveTheWizard', '$2a$12$A74tKw96m82AEZpJrIEQxecZGscKayJD/hD5/I6DuqKEJoQlAlNYO', '2017-12-25 00:00:00', 'images/mage-1.jpg', 1, 1, 0, 'A mystic scholar with an unfortunate curse seeking a demon confidant to help decipher ancient tomes. Enjoys moonlit rituals and deciphering cryptic runes. If you can break the curse or at least provide some spellbinding company, swipe right. Beware of owl-themed puns.'),
  (2, 'MoonWitch9', '$2a$12$o2NP8ykiki.T11qRQOCnBeX68PhwXHprM/hxHkbAfqotWo2XT.vdW', '2017-12-25 00:00:00', 'images/mage-2.jpg', 1, 0, 1, 'Alchemy aficionado with a penchant for astral projections and cosmic spellcraft. On the quest for a demon partner to explore otherworldly dimensions. If you''re into starry-eyed adventures and seeking enlightenment in the ethereal realms, swipe right!'),
  (3, 'sharon123', '$2a$12$8HIQ9kqN0brBUfDigfSfB.9BlSsICw4LQ/tiw4U/zMW5QWtuTqMG6', '2017-12-25 00:00:00', 'images/mage-3.jpg', 1, 0, 0, 'A brooding necromancer in search of a demon companion for dark rituals and shadowy expeditions. Enjoys moonless nights and raising the undead. Looking for a demon with a taste for the macabre. Swipe right if you''re ready to embrace the darkness within.'),
  (4, 'Malgor_the_Mighty', '$2a$12$vpUb03L0WVHMfrHducL2SumogekzuPfh9Ych0Il8Zkt5Baqch7QZq', '2017-12-25 00:00:00', 'images/mage-4.jpg', 1, 0, 0, 'I AM MIGHTY.'),
  (5, 'Ignatius', '$2a$12$AEVcwDH6apiHoyJnZcgWaemY9gZ.fn2ZlTeQZKy.w4Pq7qptgyJtG', '2017-12-25 00:00:00', 'images/mage-5.jpg', 1, 0, 0, 'Wielding the abyssal arts, I seek a demon to dance with me in the moon''s shadow. Enjoys plotting world domination, summoning eldritch horrors, and dark poetry. Swipe right if you dare to explore the depths of your own darkness.'),
  (6, 'TheBeast666', '$2a$12$.nvgl/CiZLYqnf6zz4Iq4OUGEN72OmArjhz6j5BCyKQz6i9TCDBfS', '2017-12-25 00:00:00', 'images/entity-2.jpg', 0, 0, 0, '3,000 year old primordial demon looking for a powerful wizard to show me a thing or two.<ul><li>Doesn''t have human sacrifices but wants them someday.</li><li>NO TORIES.</li></ul>'),
  (7, 'Paymon', '$2a$12$4luxIrDKiU.bpasgzWuRwurBeGX8JNc7Q.taioE6nP3ZUGsN8cH2i', '2017-12-25 00:00:00', 'images/entity-1.jpg', 0, 0, 0, 'No time-wasters: if you''re not looking to form a contract, move along please! I am an astral entity of unimaginable horror, looking for a mage who has already forfeit their sanity in the pursuit of the forbidden knowledge. If your opener mentions DMT you will be blocked for unoriginality.'),
  (8, 'BeckyTheDryad', '$2a$12$M3CzlEMu7CqCJseuus70Ne4xAKFh795psGCgTQc1diZVL5UiYPqG.', '2017-12-25 00:00:00', 'images/entity-4.jpg', 0, 0, 0, 'Progressive wood spirit looking for a conscientious mage who cares about the environment and animal rights. Only vegans need apply, and any unsolicited pictures of your wand will get you blocked and reported.'),
  (9, 'Azazel', '$2a$12$fNhJ0RA8nAK.FVbYARXr7e8pMpR8hgLl11xkBpRdIyubrgapb6NeK', '2017-12-25 00:00:00', 'images/entity-3.jpg', 0, 0, 0, 'I just got out of a 300 year contract, so I''m really looking to take things slow. That said, if the right sorcerer were to show up, who knows haha 🤣'),
  (10, 'The_Bone_Daddy', '$2a$12$lThFqSHOxWqsWU52CUcWeOcDWE70H6GedGDdRBk7QEb/1gfb/PBzm', '2017-12-25 00:00:00', 'images/entity-5.jpg', 0, 0, 0, 'Ä̷̪C̷͚̀K̷̞̉ ̴̮͊Ň̷̢Y̵̞͠Ȁ̸̘K̸̻̉ ̷̪͋N̴͇̋Y̷͈̽A̶̽ͅK̸̑ͅ.̵̩̀ ̶͉͂A̷̫̍C̵̤̉K̷̘̽!̵̹͛ ̸̬͆A̴̡̓Ḵ̴͝Ǎ̷̬Ḵ̵̔Ä̶̮́C̴̞͘K̷͚̿!̵̲̎ ̷̲̇A̷̠̎C̷̺̒K̷͉͝ ̴͖̅A̸͙̋C̵̜̀K̴͖̓,̶̜̎ ̴̬͝A̸̺͂C̴̪̿K̶̫͐ ̶̻́A̷̲̕C̵͍̕K̷̢̃!̴̱͝ ̴͙̈N̴̡̈Ỵ̵̑Ả̶̪K̴͓͆ ̵̞̀Ć̷͖K̴͔̕G̵̯̀H̷̥͛A̶͖̍K̸͕̀ ̸͎̈́G̷͚͊H̶̤̐Ã̵̘K̸̪̐Ý̸̘Ă̴͜K̶̢͠ ̸̢̊A̵̮͌C̶̠̐K̷̟̐Ȧ̵̯C̶͍͝Ḱ̴̩!̶͖̆ ̶̩̐A̵̹͑C̷͍͝K̵̤͆ ̸̱̎N̶͓̍Y̶̻͐Á̸͚K̵̯͘ ̴̯̇N̸̹̎Ỵ̸͝A̵̗̒K̵̬̇.̷͓̃ ̵͇͘A̸͉̽C̶̠͋K̷̏͜!̴͉̂ ̷͍̈́A̴̭͑Ḱ̷̯A̷͈̔K̸̺͆Á̵̰C̴̣̏Ḱ̸̭!̵̒͜ ̸͈̒A̶̗͋C̶͖͋K̷̫̕ ̵͖͛A̷͜͝Č̴̱K̷̠̍,̴̲͝ ̴̝̓A̷̰̽C̴͍͛K̵̖̒ ̷͉̉Ả̷̲C̷͕̾K̵͚̄!̷͔̔ ̴͈̃N̶͕̿Y̶̙͗A̶̖͛K̶͈̀ ̸͈͑C̶̨̍K̴͔̑Ḡ̴̘Ḫ̴̐A̴̗͘K̷̰̑ ̵͙͆G̵̬̋H̵͍̔A̷̠͝K̶̼͂Y̴̘̑Á̷̝K̸͇̓ ̸̣̆A̸͍̐C̴̺̀K̷̞͠Ạ̷̒C̷͈͆K̴̠͆!̸̨̛ ̴̧͑A̷̢͆Ć̶̠Ḱ̴̼ ̵̠͊Ń̴̜Ÿ̷̩Á̵̹K̷̝̄ ̶͙͊Ṅ̸̼Y̸͓͌A̸͍̚K̴͚̄.̷͍̋ ̸̹͌Å̵͙C̵̙̍K̵̙͊!̸̱͂ ̵͓̒Ḁ̴͠K̶̩̕À̸̧K̵̰͛Å̴̳C̵̡̚K̵̜̕!̷͇̀ ̸̭̅A̵̙͠C̶̙̾K̵̘̈ ̴͔̎A̸̫̍C̷͈̃K̸͎̈́,̶̞̅ ̵͉̌Ä̸͓́C̴̟̕K̵͚͊ ̶͚͑Ạ̵̏C̷̺̃K̵̥̍!̵͈̈́ ̴̩͛N̶̺̑Y̷͚̑Ă̴̖K̶͓͊ ̴̺̌C̷͎̋K̶͙̂G̶̦͂H̴̱́A̸͎̍K̷͒͜ ̶̞̆G̶̝̀Ḩ̵̐A̸̰͑K̴̏ͅY̵̩̓Ȧ̶̪K̴̮̓ ̶͔̅Ả̷̖C̷͈̒K̵̮̋Ǎ̵͕C̸͙̎K̶̛̦!̷̩͘')
ON CONFLICT DO NOTHING;

COMMIT;